[package]
name = "prr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
subprocess = "0.2.9"
tokio = { version = "0.2.4", features = ["full"] }
